# gills2 build workflow based on node.js template
#
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  # build job
  build:
    runs-on: ubuntu-latest
    # todo: could be simplified
    strategy:
      matrix:
        node-version: [19.x]
    # steps
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: npm test --if-present
    - name: "Upload build artifact"
      uses: actions/upload-pages-artifact@v1
      with:
        path: './dist'

  # deploy job
  deploy:
    runs-on: ubuntu-latest
    # dependency to build job
    needs: build
    # grant GITHUB_TOKEN permissions required to make a deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    # deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # steps
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
