# gills2 build workflow based on node.js template
#
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build + Upload Gills2 Site

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  # build job
  build:

    # os
    runs-on: ubuntu-latest

    # steps
    steps:
      # checkout
    - uses: actions/checkout@v3

      # node
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 19.x
        cache: 'npm'

      # install deps
    - run: npm ci
    - run: ./build.sh

      # test
    - run: npm test --if-present

      # upload
    - name: "Upload build artifact"
      uses: actions/upload-pages-artifact@v1
      with:
        path: './dist'

